name: Trading Bot
on:
  schedule:
    # For UTC+7 (Jakarta), subtract 7 hours from desired time
    - cron: '30 */23 * * *'  # Runs at :30 every hour YOUR TIME (e.g., 08:30 WIB = 01:30 UTC)
  workflow_dispatch:  # Allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}  # Uses Personal Access Token (PAT)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install ccxt python-dotenv

      - name: Run Trading Bot
        env:
          INDODAX_API_KEY: ${{ secrets.INDODAX_API_KEY }}
          INDODAX_SECRET_KEY: ${{ secrets.INDODAX_SECRET_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GITHUB_REPOSITORY: ${{ github.repository }}  # Add this line
          PAT: ${{ secrets.PAT }}  # Add this line
        run: python bot.py
