name: Trading Bot
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes (UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}  # Keep PAT here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install ccxt python-dotenv

      - name: Run Trading Bot
        env:
          INDODAX_API_KEY: ${{ secrets.INDODAX_API_KEY }}
          INDODAX_SECRET_KEY: ${{ secrets.INDODAX_SECRET_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PAT: ${{ secrets.PAT }}  # Crucial for git push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin main  # Add this before running
          python bot.py
